### ISSUE TITLE
Compiling front matter in jade throwing errors

### ISSUE THREAD

**Issue by alastair38** [carrot/roots-dynamic-content#31]
As with the previously reported issue #15 I was receiving the following error using the dynamic content extension. 

```
Warning: missing space before text for line 2 of jade file "/Users/.../example-blog/views/posts/hello-world.jade"
✘ Error: Error: /Users/.../example-blog/views/posts/hello-world.jade:3
    1| ---
    2| title: 'Hello world!'
  > 3| date:  1/2/2014
    4| ---
    5|
    6| :markdown

Unexpected token `tag` expected `text`, `code`, `:`, `newline` or `eos`

Potentially unhandled rejection [5] Error: /Users/.../example-blog/views/posts/hello-world.jade:3
    1| ---
    2| title: 'Hello world!'
  > 3| date:  1/2/2014
    4| ---
    5|
    6| :markdown

Unexpected token `tag` expected `text`, `code`, `:`, `newline` or `eos`
  at Parser.tag [...]
```
The extension is installed through app.coffee as per the documents.  The only way I found to get the project to compile was to also install the roots-yaml extension and update the app.coffee file with 

```
yaml  = require 'roots-yaml'

module.exports =
  extensions: [yaml()]

  # everything else...
```

Not sure where the problem exists, but this is how I worked around it.

**Comment by jenius** [comment]
Did you initialize dynamic content in the `extensions` array in your `app.coffee` file? I was only able to replicate the error when doing this. Once I loaded dynamic content correctly, everything compiled and there was no error.

If you have done this and are still getting the error, please paste your `app.coffee` file here

**Comment by alastair38** [comment]
OK, I've tried it with a new roots project now and if the app.coffee file is as follows, I'll get the error
```
axis         = require 'axis'
rupture      = require 'rupture'
autoprefixer = require 'autoprefixer-stylus'
js_pipeline  = require 'js-pipeline'
css_pipeline = require 'css-pipeline'
dynamic_content = require 'dynamic-content'

module.exports =
  extensions: [dynamic_content()]

module.exports =
  ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf']
 
  extensions: [
    js_pipeline(files: 'assets/js/*.coffee'),
    css_pipeline(files: 'assets/css/*.styl')
  ]

  stylus:
    use: [axis(), rupture(), autoprefixer()]
    sourcemap: true

  'coffee-script':
    sourcemap: true

  jade:
    pretty: true
```

If app.coffee is like this 

```
axis         = require 'axis'
rupture      = require 'rupture'
autoprefixer = require 'autoprefixer-stylus'
js_pipeline  = require 'js-pipeline'
css_pipeline = require 'css-pipeline'
dynamic_content = require 'dynamic-content'

module.exports =
  ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf']
 
  extensions: [
    dynamic_content(),
    js_pipeline(files: 'assets/js/*.coffee'),
    css_pipeline(files: 'assets/css/*.styl')
  ]

  stylus:
    use: [axis(), rupture(), autoprefixer()]
    sourcemap: true

  'coffee-script':
    sourcemap: true

  jade:
    pretty: true
```
Everything compiles.  

Unless I've misconstrued your comment, shouldn't the second version of the app.coffee file throw the error instead of the first?

**Comment by alastair38** [comment]
Sorry, didn't mean to close that!

**Comment by jenius** [comment]
The first `app.coffee` behaves as expected and does not compile the front matter since `dynamic_content` has not been loaded as an extension.

The second `app.coffee` also behaves as expected and compiles the front matter since `dynamic_content` is being loaded and used.

Everything seems to be in good working order here!
