### ISSUE TITLE
Roots Dynamic Content issue

### ISSUE THREAD

**Issue by benod3107** [carrot/roots-dynamic-content#34]
Hi,
I tried for ages to get this to work by following the instructions but had no luck. I did however get it to work by running the following:

 $ npm i dynamic-content --save

In app.coffee instead of requiring the following:
dynamic_content = require 'dynamic-content'

I required it this way
dynamic = require 'dynamic-content'

& I changed the extension as follows:

module.exports =
  extensions: [dynamic_content()]

To this:

module.exports =
  extensions: [dynamic()] 

  # everything else...

**Comment by kylemac** [comment]
@benod3107 as far as i can tell, those two things are 100% equivalent. perhaps there was some other error you ended up solving by renaming by renaming the variable.
