### ISSUE TITLE
Deep Nesting - Dynamic Content

### ISSUE THREAD

**Issue by benod3107** [carrot/roots-dynamic-content#35]
Hi,
When and how would I implement the below example?
------------------------------------------------------------------------
#news
  each post in site.posts.news
    ...

#hires
  each post in site.posts.hires
    ...

#doge
  each post in site.posts.doge
    ...

**Comment by jenius** [comment]
This is the basic functionality of dynamic content, we have documentation for this!

https://github.com/carrot/roots-dynamic-content/blob/master/docs/intro.md
