### ISSUE TITLE
Incompatibility with css-pipeline

### ISSUE THREAD

**Issue by FranzSkuffka** [carrot/roots-dynamic-content#36]
The `css()` helper of the css-pipeline does not respect the path of compiled dynamic content entries. I am going to hard-code this to a relative url now in my template. Am I missing something here or is there a better way to do this?

**Comment by kylemac** [comment]
i'm not sure how these things relate? mind giving an example with the paths that are coming out?

**Comment by FranzSkuffka** [comment]
views/index.jade compiles to index.html
```
...

!=css()

// output: css/master.css
````
<hr>


de/index.jade compiles to de/index.html
```
@extend ../layout.jade

...

!=css()

// output: css/master.css => 404 Error
// should be: ../css/master.css 
````

**Comment by jenius** [comment]
Use `!= css('/')` to load from absolute path 😁
