### ISSUE TITLE
conflict with other roots extensions

### ISSUE THREAD

**Issue by ayenzky** [carrot/roots-dynamic-content#37]
When I tried to use both dynamic-contents and roots-collections one of them will not work. Is there a way to solve this problem?

**Comment by jescalan** [comment]
Why would you need to use both?

**Comment by ayenzky** [comment]
I need to use the write function which compile all markdown files to json and the deep nesting categorization since this function is not on the roots-collections. Im using the roots-cms-example which using the (.md) markdown files.

**Comment by jescalan** [comment]
You can just use dynamic content for this, is there any particular reason you also need `roots-collections`?

**Comment by ayenzky** [comment]
Yes, since `roots-cms-example` only support `.md & json` files in dynamic content editing on` cms`. Sorting is also important that I need from the `roots-collections` and also the assigning of layout of the post. Although the front-matter itself has it's way on assigning a layout but it's in jekyll.

**Comment by jescalan** [comment]
You can sort without `roots-collections` by using [`Array.prototype.sort`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort). You can use markdown by installing `marked` and changing the file extension to `.md`. No idea what you are saying with the jekyll piece, this project has nothing to do with jekyll...

Another solution is that you could pull request the json write into roots-collections, if that's easier for you!

**Comment by ayenzky** [comment]
Ok thanks..I will try.
