### ISSUE TITLE
can not make japanese content

### ISSUE THREAD

**Issue by rirufa** [carrot/roots-dynamic-content#38]
I did intro.md and write some posts in Japanse and save as UTF-8 Signatuer. I got error message 'Cannot read property 'posts' of undefined' when compile

I tried save as Unicode without bom. It isn't resloved. Also, I tried write english senetence and save as UTF-8 Signatuer. It failed.

OS:Windows 10.0.14393
node.js:v6.9.2

**Comment by jescalan** [comment]
I'm not sure how to fix, or even how to replicate this. Could you just enter some text into a normal text editor and save it to see if it works?

**Comment by rirufa** [comment]
I wrote it other text editor --- notepad2 and it worked because it does not have BOM.
But when I wrote text on notepad as UTF-8, it did not work because it have BOM.

**Comment by jescalan** [comment]
Ah thats probably because we read all files in as utf8. We can't really change this, so make sure to write your files in utf8! Atom is a great text editor that should work on all operating systems if you're after one, and it will always save as utf8

**Comment by rirufa** [comment]
I understood the reason you can't fix it and I don't wish that you fix it. But I wish that you write its behavior to intro.md because I spent long time to resolve the problem and understand its behavior.

**Comment by jescalan** [comment]
You mean you want me to add that you should use utf8 text files to the readme? That seems fair enough. Would you like to add it, since you discovered it? You can make a pull request to put it into the readme 😁

**Comment by rirufa** [comment]
I'm sorry for my unfair behavior. I will make pull request.

**Comment by jescalan** [comment]
Sounds good, thank you so much for your politeness and willingness to help! 👬
